const bi = (en, zh) => ({ en, zh })

export const publications = [
  { year:'2026', journal:'Materials and Structures', title:'Low-carbon SCMs mitigate chloride attack and calcium leaching-induced degradation: physicochemical mechanisms and multiscale modeling', authors:'Chen D, Guo W, Duan B, et al.', volume:'59(3), 157', role:bi('First author','第一作者'), doi:'10.1617/s11527-026-02981-1' },
  { year:'2025', journal:'Materials Today Communications', title:'Multiscale modeling reveals coupled chloride-sulfate attack mechanisms in coastal bridges: from pore evolution to service life prediction', authors:'Chen D, Chen D, Guo W, et al.', volume:'113508', role:bi('First author','第一作者'), doi:'10.1016/j.mtcomm.2025.113508' },
  { year:'2025', journal:'Sustainable Chemistry and Pharmacy', title:'Microstructural and mechanical evolution of recycled fiber-reinforced tunnel slag concrete under wet-dry cycles', authors:'Huang H, Du C, Yi F, Chen D, Zhang C.', volume:'43, 101905', role:bi('Corresponding author','通讯作者'), doi:'10.1016/j.scp.2025.101905' },
  { year:'2025', journal:'中南大学学报（自然科学版）', title:'水泥基材料细观结构导致的氯离子传输不确定性研究', authors:'陈定市, 郭文华.', volume:'56(01), 156–172', role:bi('First author','第一作者'), doi:null },
  { year:'2025', journal:'铁道科学与工程学报', title:'重载铁路钢筋混凝土梁桥氯盐侵蚀-疲劳寿命评估', authors:'陈定市, 段斌鑫, 郭文华.', volume:'1–13', role:bi('First author','第一作者'), doi:null },
  { year:'2024', journal:'Construction and Building Materials', title:'Mesoscopic characteristics and spatiotemporal variability of chloride transport in concrete', authors:'Chen D, Guo W, Wu B, Ye T.', volume:'415, 135081', role:bi('First author','第一作者'), doi:'10.1016/j.conbuildmat.2024.135081' },
  { year:'2024', journal:'Thin-Walled Structures', title:'Mesoscopic statistics-based probability characteristics of chloride transport and reliability-based corrosion initiation life of bridge tower', authors:'Chen D, Guo W, Quan X, et al.', volume:'198, 111680', role:bi('First author','第一作者'), doi:'10.1016/j.tws.2024.111680' },
  { year:'2024', journal:'Construction and Building Materials', title:'Mechanistic modeling for coupled chloride-sulfate attack in cement-based materials', authors:'Chen D, Guo W, Chen D, et al.', volume:'455, 139231', role:bi('First author','第一作者'), doi:'10.1016/j.conbuildmat.2024.139231' },
  { year:'2024', journal:'Journal of Building Engineering', title:'Mesostructure-induced uncertainty of chloride transport in concrete', authors:'Chen D, Guo W, Guo L, et al.', volume:'98, 111337', role:bi('First author','第一作者'), doi:'10.1016/j.jobe.2024.111337' },
  { year:'2024', journal:'Engineering Failure Analysis', title:'Novel epoxy resin-bonded sand system: Mechanical strength, deterioration resistance, and failure mechanism', authors:'Shi J, Chen D, Yu Z.', volume:'158, 108020', role:bi('Corresponding author','通讯作者'), doi:'10.1016/j.engfailanal.2024.108020' },
  { year:'2024', journal:'Case Studies in Construction Materials', title:'Data-driven predicting of bond strength in corroded BFRP concrete structures', authors:'Li B, Zhang J, Qu Y, Chen D, Feng C.', volume:'21, e03638', role:bi('Corresponding author','通讯作者'), doi:'10.1016/j.cscm.2024.e03638' },
  { year:'2023', journal:'Construction and Building Materials', title:'Experimental and modelling investigation on chloride transport and flexural behaviour of RC beams subjected to simultaneous deteriorating factors of carbonation, FT cycles and multi-type sustained stress', authors:'Chen D, Guo W, Kang J, Shi J.', volume:'397, 132305', role:bi('First author','第一作者'), doi:'10.1016/j.conbuildmat.2023.132305' },
  { year:'2023', journal:'Engineering Failure Analysis', title:'Service life prediction and time-variant reliability of reinforced concrete structures in harsh marine environment considering multiple factors: A case study for Qingdao Bay Bridge', authors:'Chen D, Guo W, Wu B, Shi J.', volume:'154, 107671', role:bi('First author','第一作者'), doi:'10.1016/j.engfailanal.2023.107671' },
  { year:'2022', journal:'Journal of Building Engineering', title:'Experimental study and modelling of concrete carbonation under the coupling effect of freeze-thaw cycles and sustained loads', authors:'Chen D, Liu S, Shen J, et al.', volume:'52, 104390', role:bi('First author','第一作者'), doi:'10.1016/j.jobe.2022.104390' },
  { year:'2022', journal:'Structures', title:'Experimental and simulation study on chloride diffusion in unsaturated concrete under the coupled effect of carbonation and loading', authors:'Chen D, Feng Y, Shen J, et al.', volume:'43, 1356–1368', role:bi('First author','第一作者'), doi:'10.1016/j.istruc.2022.07.031' },
  { year:'2021', journal:'Construction and Building Materials', title:'A meso-stochastic research on the chloride transport in unsaturated concrete', authors:'Chen D, Yang K, Hu D, Shi J.', volume:'273, 121986', role:bi('First author','第一作者'), doi:'10.1016/j.conbuildmat.2020.121986' },
  { year:'2021', journal:'Journal of Building Engineering', title:'Study on the bearing capacity and chloride ion resistance of RC structures under multi-factor corrosive environment and continuous load', authors:'Chen D, Sun G, Hu D, Shi J.', volume:'44, 102990', role:bi('First author','第一作者'), doi:'10.1016/j.jobe.2021.102990' },
]

const eng = (id, period, title, phase, role, type, span, location, scope, highlights, visual) => ({ id, period, title, phase, role, type, span, location, scope, highlights, visual })

export const engineeringProjects = [
  eng('pingnan','2022.02 — 2022.08',bi('Pingnan–Rongxian Expressway Cable-Stayed Bridge','全州至容县公路（平南至容县段）斜拉桥'),bi('Construction documents','施工图设计'),bi('Discipline lead','分项负责人'),bi('Hybrid steel-box-girder cable-stayed bridge','钢箱混合梁斜拉桥'),bi('636 m main span','主跨 636 m'),bi('Guangxi, China','中国 · 广西'),bi('Led the structural design, calculation and optimisation of the main towers.','负责主塔结构设计、计算与优化。'),[bi('Long-span tower design','大跨径主塔设计'),bi('Construction-document delivery','施工图成果交付')],'cable'),
  eng('qinyang','2021.05 — 2022.08',bi('Qinyang–Yichuan Expressway Yellow River Bridge','沁阳至伊川高速公路黄河特大桥'),bi('Construction documents','施工图设计'),bi('Discipline lead','分项负责人'),bi('Multi-span steel–concrete composite girder bridge','多跨连续钢混组合梁桥'),bi('100 m main span · approx. 7 km total','主跨 100 m · 全长约 7 km'),bi('Henan, China','中国 · 河南'),bi('Led the substructure design, structural calculation and optimisation of the main bridge.','负责主桥下部结构设计、计算与优化。'),[bi('Large-scale substructure system','大型桥梁下部结构'),bi('Long corridor coordination','超长桥梁设计协调')],'girder'),
  eng('xinguanniao','2022.03 — 2022.08',bi('Xinguanniao Han River Bridge','新关庙汉江大桥'),bi('Construction-document consultancy','施工图设计咨询'),bi('Discipline lead','分项负责人'),bi('Twin-tower, twin-plane self-anchored suspension bridge','双塔双索面自锚式悬索桥'),bi('(45+75+180+75+55) m','(45+75+180+75+55) m'),bi('Hubei, China','中国 · 湖北'),bi('Performed independent design review, structural checking and optimisation for the construction-document scheme.','开展施工图设计咨询计算、复核与优化。'),[bi('Self-anchored system','自锚式体系'),bi('Independent design verification','独立设计复核')],'suspension'),
  eng('uchar','2020.08 — 2021.05',bi('Uchar Bridge, DASU–KKH Relocation','DASU–KKH 改建项目 Uchar 大桥'),bi('Preliminary & construction documents','初步设计及施工图设计'),bi('Bridge lead','桥梁负责人'),bi('Prestressed-concrete rigid-frame bridge','预应力混凝土连续刚构桥'),bi('180 m main span','主跨 180 m'),bi('Khyber Pakhtunkhwa, Pakistan','巴基斯坦 · 开伯尔-普什图省'),bi('Led preliminary and detailed design under AASHTO standards; introduced an innovative horizontal bottom-slab tendon arrangement.','按 AASHTO 规范负责初步及施工图设计，创新采用水平底板索结构。'),[bi('AASHTO-compliant design','全 AASHTO 规范'),bi('First overseas application of the tendon scheme','该结构国外首次采用')],'girder'),
  eng('barseen','2020.08 — 2021.05',bi('Barseen Bridge, DASU–KKH Relocation','DASU–KKH 改建项目 Barseen 大桥'),bi('Preliminary & construction documents','初步设计及施工图设计'),bi('Bridge lead','桥梁负责人'),bi('Deck-type reinforced-concrete arch bridge','上承式钢筋混凝土拱桥'),bi('150 m main span','主跨 150 m'),bi('Khyber Pakhtunkhwa, Pakistan','巴基斯坦 · 开伯尔-普什图省'),bi('Led the full preliminary and construction-document design using AASHTO standards.','按 AASHTO 规范完成初步设计与施工图设计。'),[bi('Mountainous hydropower corridor','山地水电工程走廊'),bi('International multidisciplinary delivery','国际工程协同')],'arch'),
  eng('dogah','2020.08 — 2021.05',bi('Dogah Bridge, DASU–KKH Relocation','DASU–KKH 改建项目 Dogah 大桥'),bi('Preliminary & construction documents','初步设计及施工图设计'),bi('Bridge lead','桥梁负责人'),bi('Highway bridge','公路桥梁'),bi('Project data to be supplemented','跨径资料待补充'),bi('Khyber Pakhtunkhwa, Pakistan','巴基斯坦 · 开伯尔-普什图省'),bi('Led design delivery as part of the KKH relocation bridge package under AASHTO standards.','作为 KKH 改建桥梁群负责人，按 AASHTO 规范完成设计交付。'),[bi('International bridge package','国际桥梁群项目'),bi('AASHTO design workflow','AASHTO 设计流程')],'girder'),
  eng('linyi','2019.01 — 2019.05',bi('Linyi Yellow River Bridge','临猗黄河大桥'),bi('Preliminary & construction-document consultancy','初步设计及施工图设计咨询'),bi('Discipline lead','分项负责人'),bi('Continuous composite steel-box-girder bridge','等高连续组合钢箱梁桥'),bi('(112+5×128+5×6×128) m','(112+5×128+5×6×128) m'),bi('Shanxi, China','中国 · 山西'),bi('Undertook seismic review calculations and prepared the formal calculation report.','承担代部审查咨询抗震计算并编制计算报告。'),[bi('Extra-long multi-span system','超长联多跨体系'),bi('Seismic design review','抗震设计审查')],'girder'),
  eng('caodu','2018.04 — 2018.08',bi('Caodu River Bridge','漕渡河特大桥'),bi('Preliminary design','初步设计'),bi('Discipline lead','分项负责人'),bi('Deck-type concrete-filled-steel-tube truss arch bridge','上承式钢管混凝土桁架拱桥'),bi('460 m calculated span','计算跨径 460 m'),bi('Guizhou, China','中国 · 贵州'),bi('Completed preliminary design of the main arch bridge and its approach bridges.','完成主桥及引桥初步设计。'),[bi('Large-span CFST arch','大跨钢管混凝土拱桥'),bi('Main and approach bridge integration','主引桥一体化设计')],'arch'),
  eng('xiangjiang','2017.04 — 2017.07',bi('Xiangjiang Bridge','湘江特大桥'),bi('Preliminary design','初步设计'),bi('Discipline lead','分项负责人'),bi('Steel–concrete composite cable-stayed bridge','钢—混组合梁斜拉桥'),bi('560 m main span','主跨 560 m'),bi('Guizhou, China','中国 · 贵州'),bi('Performed global modelling, structural calculations, calculation-report preparation and selected girder drawings.','负责总体建模计算、计算书编制及部分主梁图纸。'),[bi('Global structural analysis','总体结构分析'),bi('Composite-girder coordination','组合梁协同设计')],'cable'),
  eng('yangbaoshan','2017.07 — 2017.12',bi('Yangbaoshan Bridge','阳宝山特大桥'),bi('Construction documents','施工图设计'),bi('Core team member','主要参与人'),bi('Steel-truss-girder suspension bridge','钢桁梁悬索桥'),bi('650 m main span','主跨 650 m'),bi('Guizhou, China','中国 · 贵州'),bi('Designed and analysed the steel-truss girder for China’s first suspension bridge erected using the AS method.','完成钢桁架主梁设计与计算；该桥为国内首次采用 AS 法架设的悬索桥。'),[bi('First AS-method suspension bridge in China','国内首座 AS 法架设悬索桥'),bi('Steel-truss-girder design','钢桁梁设计')],'suspension'),
  eng('baihe','2017.03 — 2017.12',bi('Chengdu Xinjin Baihe Bridge','成都新津白鹤大桥'),bi('Construction documents','施工图设计'),bi('Discipline lead','分项负责人'),bi('Flying-swallow asymmetric parabolic steel arch bridge','飞燕式偏态抛物线钢拱桥'),bi('(35+95+95+35) m','(35+95+95+35) m'),bi('Sichuan, China','中国 · 四川'),bi('Led scheme development and construction-document design of the main arch.','负责方案设计及施工图设计主拱分项。'),[bi('Asymmetric parabolic arch','偏态抛物线拱'),bi('Main-arch detailed design','主拱施工图设计')],'arch'),
  eng('wuxue','2016.10 — 2018.10',bi('Wuxue Yangtze River Highway Bridge','湖北武穴长江公路大桥'),bi('Construction documents','施工图设计'),bi('Discipline lead','分项负责人'),bi('Hybrid-girder cable-stayed bridge','混合梁斜拉桥'),bi('808 m main span','主跨 808 m'),bi('Hubei, China','中国 · 湖北'),bi('Led tower design, global calculation and construction-document delivery for the landmark Yangtze crossing.','作为主塔分项负责人，完成总体计算、主塔结构分析与施工图设计。'),[bi('808 m landmark span','808 m 标志性跨径'),bi('Global analysis and tower delivery','总体与主塔设计交付')],'cable'),
  eng('matihe','2015.03 — 2016.07',bi('Mati River Bridge','马蹄河大桥'),bi('Construction-document consultancy','施工图设计咨询'),bi('Core team member','主要参与人'),bi('Deck-type reinforced-concrete arch bridge','上承式钢筋混凝土拱桥'),bi('180 m main span','主跨 180 m'),bi('China','中国'),bi('Contributed to construction-document design review for the main arch erected by cable-stayed cantilever casting.','参与施工图设计咨询；主拱采用斜拉扣挂悬臂浇筑施工。'),[bi('Pioneering highway construction method','公路行业同类第一'),bi('Arch construction consultancy','拱桥施工设计咨询')],'arch'),
]

const res = (id, period, title, programme, role, budget, code, description, contributions) => ({ id, period, title, programme, role, budget, code, description, contributions })
export const researchProjects = [
  res('nsfc','2022.10 — 2025.02',bi('Fatigue damage and residual-life assessment of prestressed concrete girder bridges under coupled environment and heavy traffic','考虑环境和重载耦合作用的预应力砼梁桥疲劳损伤机理分析及剩余寿命评估'),bi('National Natural Science Foundation of China','国家自然科学基金面上项目'),bi('Core participant','主要参与人'),bi('CNY 560,000','56 万元'),'52078489',bi('Fatigue damage mechanisms, deterioration modelling and residual-life assessment under coupled environmental and heavy-load actions.','研究环境侵蚀与重载耦合作用下疲劳损伤机理、性能退化及剩余寿命。'),bi('Completed approximately half of the project’s substantive research tasks.','完成约半数实质性研究内容。')),
  res('keyrd','2022.11 — 2024.11',bi('Intelligent testing equipment and platform for service capacity of major land-transport structures','陆路交通关键大型构造物服役能力智能测试装备与平台研发'),bi('National Key R&D Programme · Task 5','国家重点研发计划 · 课题 5'),bi('Participant','参与人'),bi('CNY 22 million','2200 万元'),'2021YFB2601005',bi('Development of intelligent testing equipment and platforms for evaluating large transport structures in service.','研发陆路交通大型构造物服役能力智能测试装备与平台。'),bi('Contributed research and organised interim, annual and final technical reports.','参与部分研究及中期、年度、结题报告整理。')),
  res('steelroad','2022.10 — Present',bi('Optimisation of prefabricated steel road-deck systems','装配化钢结构路面优选方法研究'),bi('CCCC FHCC Science & Technology Innovation Fund','中交一公院科技创新基金'),bi('Principal investigator','主持'),bi('CNY 400,000','40 万元'),bi('Industry-funded project','企业委托项目'),bi('Development and performance-based selection of a prefabricated bridge-type road system for permafrost subgrades.','研发适用于冻土路基的装配化桥式路面结构及优选方法。'),bi('Responsible for overall research design, modelling, evaluation and delivery.','负责总体方案、建模、评价与成果交付。')),
  res('csu','2023.01 — 2024.12',bi('Multiscale and probabilistic modelling of chloride ingress under coupled harsh-environment actions','复杂环境多场耦合作用下混凝土结构氯盐侵蚀多尺度模拟与概率模型研究'),bi('Fundamental Research Funds for the Central Universities','中央高校基本科研业务费专项'),bi('Principal investigator','主持'),bi('University-funded','校级资助'),'2023ZZTS0373',bi('Multiscale chloride-transport models and probabilistic quantification of mesostructure- and environment-induced uncertainty.','构建复杂环境氯盐侵蚀多尺度模型与概率模型。'),bi('Led model development, numerical simulation, uncertainty analysis and publication.','主持模型构建、数值模拟、不确定性分析与论文产出。')),
  res('crcc','2020.08 — Present',bi('Key technologies for large-span bridge construction in complex reservoir environments in Pakistan','巴基斯坦库区复杂环境下大跨桥梁建造关键技术'),bi('China Railway Construction Corporation Research Programme','中国铁建股份有限公司科研计划'),bi('Core participant','主要参与人'),bi('CNY 2 million','200 万元'),'2021-C01',bi('Key design, construction and durability technologies for large-span bridges in complex reservoir environments.','研究复杂库区大跨桥梁设计、建造及耐久性关键技术。'),bi('Contributed proposal preparation, project establishment and continuing research.','完成课题申报、立项并持续参与研究。')),
  res('shaanxi','2020.01 — 2022.12',bi('Force mechanism and design method of main-cable wires in AS-erected suspension bridges','AS架设悬索桥主缆钢丝受力机理与设计方法研究'),bi('Shaanxi Natural Science Basic Research Programme','陕西省自然科学基础研究计划'),bi('Core participant','主要参与人'),bi('CNY 50,000','5 万元'),'2021JM-606',bi('Mechanical behaviour and design methodology of main-cable wires during AS-method suspension-bridge erection.','研究 AS 法架设过程中主缆钢丝受力机理与设计方法。'),bi('Participated in proposal preparation and technical research.','参与课题申报与研究。')),
  res('dept','2017.10 — 2019.11',bi('Integrated joint technologies for extra-long continuous rigid-frame bridges with ultra-high piers','超长联超高墩大跨径连续刚构综合节点技术研究'),bi('Shaanxi Provincial Department of Transport Programme','陕西省交通厅科技项目'),bi('Core participant','主要参与人'),bi('CNY 2.8 million','280 万元'),'12-19K',bi('Integrated connection and structural technologies for extra-long, ultra-high-pier continuous rigid-frame bridges.','研究超长联、超高墩、大跨径连续刚构综合节点技术。'),bi('Conducted structural calculations and contributed to subtask delivery.','参与相关计算和子课题研究。')),
  res('mot','2013.10 — 2017.10',bi('Damage and load-carrying-capacity degradation of concrete bridges','混凝土桥梁结构损伤及承载力衰减研究'),bi('Ministry of Transport Applied Basic Research Programme','交通运输部应用基础研究项目'),bi('Core participant','主要参与人'),bi('CNY 800,000','80 万元'),'2013 319 812 100',bi('Experimental and numerical investigation of damage evolution and load-carrying-capacity degradation in concrete bridges.','研究混凝土桥梁损伤演化与承载力衰减。'),bi('Designed experiments, developed theoretical models and simulations, and prepared the final report.','完成试验方案、理论模型、数值模拟及结题报告。')),
]
